FROM php:5.6

RUN apt-get update
RUN apt-get install unzip -y
RUN apt-get install git -y
RUN apt-get install libxml2-dev -y
RUN apt-get install -y curl
RUN pecl install xdebug
RUN curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer
